JuliaGeometry/GeometryBasics.jl

- src/basic_types.jl
https://github.com/SimonDanisch/GeometryBasics.jl/pull/8#discussion_r313939240
> fix MultiPoint point type

- Project.toml
You can't have GeomBasics and StatsMakie together without this.
> Bump Tables compat

- docs/make.jl
- docs/src/api.md
- docs/src/decomposition.md
- docs/src/distancefields.md
- docs/src/implementation.md
- docs/src/meshes.md
- docs/src/metadata.md
- docs/src/polygons.md
- docs/src/primitives.md
- docs/src/rectangles.md
- src/geometry_primitives.jl
- src/lines.jl
- src/meshes.jl
- src/metadata.jl
- src/offsetintegers.jl
- src/rectangles.jl
- src/triangulation.jl
- src/viewtypes.jl
Builds on the `sd/finish` branch.  Adds a couple of documentation pages with not much on there yet.
cc: @Tokazama
> Prototype docs

- README.md
Also make the badges work with documenter
> fix dev link in readme

- README.md
Follow up on #37, which doesn't seem to render on GitHub or Documenter.
> fix documentation badges

- Project.toml
- src/rectangles.jl
- test/geometrytypes.jl
- test/runtests.jl
Commits best viewed separately, since the last one is just whitespace.
Hoping this will get coverage over 50% ;)
> add a few tests on Rect and Line

- .travis.yml
- Project.toml
`hasproperty` is required and only 1.2+
> Bump minimum Julia to 1.2

- test/geometrytypes.jl
- test/runtests.jl
Covered few functions in rectangles.jl
> Improve tests coverage

- src/GeometryBasics.jl
- src/precompile.jl
xref https://github.com/JuliaPlots/AbstractPlotting.jl/pull/502
> Add a couple of precompiles

- src/precompile.jl
Companion to https://github.com/JuliaPlots/AbstractPlotting.jl/pull/522
> Expand precompiles

- src/viewtypes.jl
> Fix FaceView docstring

- src/precompile.jl
From the new (but not yet released) `@snoopi_deep`
> Add a few more precompiles

- src/meshes.jl
All tests passing (Julia 1.4, Ubuntu 16.04).
> Fixed the invalid keyword syntax that was causing a LoadError. 

- .gitignore
- docs/make.jl
- docs/src/metadata.md
- src/basic_types.jl
> #126 - Fix doctests

- src/GeometryBasics.jl
- src/primitives/rectangles.jl
- test/runtests.jl
Hi all,
Not sure if there's a reason this has been specifically omitted, but it seemed simple enough that I'd put it up for consideration. 
Edits welcome.
Thanks,
Oliver
> Implement area, volume functions for rectangles

- src/precompile.jl
I don't know of any problems currently, but hopefully this future-proofs you against problems.
> Warn, don't error, on precompile failures

- src/lines.jl
see https://github.com/JuliaGeometry/GeometryBasics.jl/issues/149
> fix intersects typo

- src/meshes.jl
- test/geometrytypes.jl
Correct implementation of https://github.com/JuliaGeometry/GeometryBasics.jl/pull/197
cc: @JonasIsensee
> don't convert if already of correct type

- docs/src/meshes.md
> remove an invalid reference

- src/basic_types.jl
- test/polygons.jl
- test/runtests.jl
> Fix Polygon constructor type signature
