- Project.toml
- src/basic_types.jl
- test/runtests.jl
From https://geojson.org/: GeoJSON supports the following geometry types: Point, LineString, Polygon, MultiPoint, MultiLineString, and MultiPolygon.
In this package, the only one of those not here is MultiPoint. Or did you leave it out on purpose?
> MultiPoint

- .travis.yml
- src/fixed_arrays.jl
- src/metadata.jl
- test/fixed_arrays.jl
- test/runtests.jl
> fix meta & broadcast

- src/basic_types.jl
By the way, it seems `Polytope{N}` denotes a polytope in `N` dimension, not a polytope made of `N` points since the first type argument is named `Dim`.
> Polytype -> Polytope

- src/viewtypes.jl
Overloading `show` for types is strongly discouraged. I'm currently tracking down a Julia segfault that's caused by this line.
Refs:
- https://github.com/JuliaMath/FixedPointNumbers.jl/pull/11
- https://github.com/PainterQubits/Unitful.jl/issues/321
> Delete `show(::IO, ::Type)` specialization

- README.md
- src/GeometryBasics.jl
- src/metadata.jl
- test/runtests.jl
> Add metatype for MultiPolygon and LineString

- src/basic_types.jl
Without the dashes, the docstring is printed as a single line, which makes it difficult to read.
> Improve layout of docstring

- src/rectangles.jl
This function is already exported, but the definition was missing.
> Add min Euclidean distance from rectangle

- src/geometry_primitives.jl
- src/interfaces.jl
- test/runtests.jl
PR for #69  
So this overloads the `convert_simplex()` method to break down a linestring. 
```julia
ls1=LineString([Point(1, 2), Point(4,5), Point(10, 8), Point(1, 2)])
decompose(Point{2, Int}, ls1)
6-element Array{Point{2,Int64},1}:
[1, 2]
[4, 5]
[4, 5]
[10, 8]
[10, 8]
[1, 2]
```
The repetition of Points is the only visible issue currently. Expected is: 
```julia
ls1.points.parent.data
4-element Array{Point{2,Int64},1}:
[1, 2]
[4, 5]
[10, 8]
[1, 2]
```
> Give out points of geometries

- docs/src/metadata.md
- src/metadata.jl
> Add docs for meta

- src/geometry_primitives.jl
- test/geometrytypes.jl
```julia
using Makie
using GeometryBasics
pts = rand(Point3f0, 10)
edgs  = LineFace{Int}[(1,2), (3,4)]
display(wireframe(connect(pts, edgs)))
```
did not work before this patch.
> fix minor convert_simplex method ambiguity

- Project.toml
- src/GeometryBasics.jl
- src/basic_types.jl
- src/interfaces.jl
- src/meshes.jl
- src/triangulation.jl
- src/viewtypes.jl
- test/runtests.jl
* inlines EarCut code to triangulate polygons with holes (wasn't possible to incorperate EarCut.jl directly due to circular dependency)
* fixes triangulation + coordinates + decompose to correctly build & plot polygons
> make polygon plotting work

- .travis.yml
- Project.toml
- src/meshes.jl
fixes the following error:
```julia
julia> using GeometryBasics
[ Info: Precompiling GeometryBasics [5c1252a2-5f33-56bf-86c9-59e7332b4326]
ERROR: LoadError: LoadError: syntax: invalid keyword argument syntax "pointtype"
Stacktrace:
[1] top-level scope at /home/daniel/.julia/dev/GeometryBasics/src/meshes.jl:138
[2] include(::Module, ::String) at ./Base.jl:377
[3] include(::String) at /home/daniel/.julia/dev/GeometryBasics/src/GeometryBasics.jl:1
[4] top-level scope at /home/daniel/.julia/dev/GeometryBasics/src/GeometryBasics.jl:16
[5] include(::Module, ::String) at ./Base.jl:377
[6] top-level scope at none:2
[7] eval at ./boot.jl:331 [inlined]
[8] eval(::Expr) at ./client.jl:449
[9] top-level scope at ./none:3
in expression starting at …
```
> fix precompililation error on julia < v1.5

- src/primitives/rectangles.jl
This PR removes `Quad{T}` in favor of the new `Rect3D{T}`.
> Remove Quad{T} in favor of Rect3D{T}

- src/fixed_arrays.jl
- src/rectangles.jl
Ref JuliaGeometry/GeometryTypes.jl#207.
> Remove type piracy in `isnan`

- src/geometry_primitives.jl
I noticed `mesh` in Makie sometimes take a long time to plot. This is especially apparent when animating a large, growing mesh. The problem is a type instability in `normals`, which this PR fixes.
The only change I made is that I added a function barrier. This greatly improves performance (see below).
MWE:
```julia
using BenchmarkTools
using GeometryBasics
points = [Point(rand(), rand(), rand()) for _ in 1:200]
faces = typeof(GLTriangleFace(1,2,3))[]
for u in 1:200, v in u+1:200, w in v+1:200
push!(faces, GLTriangleFace(u, v, w))
end
@benchmark normals(points, faces) samples=10 seconds=10
@benchmark normals(points, faces) samples=10 seconds=10
```
> Fix type instability in normals

- src/GeometryBasics.jl
- src/fixed_arrays.jl
- src/interfaces.jl
- src/matrices.jl
- src/meshes.jl
- src/vectors.jl
- test/geometrytypes.jl
- test/runtests.jl
This is a continuation of #93 . It supersedes #97. Addresses #91.
Now we have a single type for representing vectors in geometrical spaces, and it happens to be an alias for `SVector` (implementation detail). Additionally, we have type aliases for end users that often wish to materialize vectors with specific coordinate type and dimension. Here, we avoid partial instantiation. The aliases `Vec2` and `Vec3` are concrete vector types in 2D and 3D using double precision, and the aliases `Vec2f` and `Vec3f` are concrete vector types using single precision.
We deprecate `unit` in favor of `euclidbasis`, which is a more accurate name for the returned vectors. We add `constant` as a helper function to construct vectors with repeated coordinates. The name `constant` isn't ideal, please let me …
> Cleanup Vec aliases

- Project.toml
There was a new release of StaticArrays.jl and this packages holds back updates of some other packages downstream. I've made a PR adding CompatHelper to automate this process in the future, cf. #112.
It would be very nice to have a new release after merging this.
> bump compat for StaticArrays

- Project.toml
- src/primitives/rectangles.jl
- test/geometrytypes.jl
This will be used to avoid boxing (in the sense of `Core.Box`, a.k.a. julia#15276) in https://github.com/JuliaPlots/AbstractPlotting.jl/blob/6346fe87f18bb1df09f0065f0ad6b2b699c20b94/src/layouting/boundingbox.jl#L170-L199. I took the liberty of bumping the version to encourage a new release.
> Add isempty

- src/meshes.jl
- test/runtests.jl
When `faces` returns `nothing`, `mesh(::Meshable)` falls back on `decompose(facetype, positions)`. The fallback is missing from `mesh(::AbstractPolygon)` so the following fails:
```
julia> t = Triangle(Point2f0(0), Point2f0(1), Point2f0(1,0))
Triangle(Float32[0.0, 0.0], Float32[1.0, 1.0], Float32[1.0, 0.0])
julia> GeometryBasics.mesh(t)
ERROR: MethodError: no method matching Mesh(::Array{Point{2,Float32},1}, ::Nothing)
```
This PR adds the fallback to the `AbstractPolygon` case.
> Fix mesh(::AbstractPolygon) in case faces returns nothing

- .github/workflows/ci.yml
- Project.toml
- src/metadata.jl
- src/triangulation.jl
- test/geometrytypes.jl
- test/runtests.jl
Some fixes for `area` following discussion in #121
* `area(::AbstractVector{AbstractPoint}})` is now documented
* In particular, the doc says that a signed value is returned in the 2D case
* Fixes for custom indices (OffsetArrays is added as a test dependency)
* The 3D case now accepts vectors of any `AbstractPoint{3}` type (the 2D case already did)
There's also a broken `area` test for a vector of `PointMeta{3}`. I couldn't make it work because it needs `zero(typeof(PointMeta(0,0,0; a=1))` and it's not clear how to implement that: How should we make the zero value of the metadata?
The PR includes a fix for a related bug: `MetaFree(typeof(PointMeta(0,0,0; a=1))` used to return `3`. Now it returns `Point{3,Int64}`, I think that's what was intended? (the fix isn't enough to make `area` work …
> area and MetaFree fixes

- src/GeometryBasics.jl
Not sure why it's not being exported but I found it useful on its own so thought it might be good to export.
> Export `HyperRectangle`

- Project.toml
- src/metadata.jl
- test/runtests.jl
In StructArrays 0.5, the interface has been slightly modified (see [NEWS entry](https://github.com/JuliaArrays/StructArrays.jl/blob/master/NEWS.md#version-050)), so now it is necessary to overload `component` as well for stucts with custom layout.
This allows better StructArrays integration and makes things like `setindex!` work out of the box with `StructArray`s of meta geometries.
I've also added tests to make sure the full interface is implemented.
> fuller StructArrays integration

- src/primitives/pyramids.jl
Fixes the directions of normals of the bottom faces of a `Pyramid`. Since it's kinda hard to see - the change here is swapping `ru, rd` and `ld, lu` so that the winding directions is correct.
Mentioned in #139
> fix (generated) normals of Pyramid

- .github/workflows/ci.yml
- Project.toml
- src/viewtypes.jl
In StructArrays 0.6, StaticArrays are treated the same way as the underlying `Tuple` in terms of data storage, so one should pass the tuple of columns directly to the constructor, without having to nest `StructArray`s.
I'm dropping compatibility with the older version, because it seems tricky to support both.
> update structarrays compat

- docs/src/decomposition.md
- src/GeometryBasics.jl
- src/deprecated.jl
- src/fixed_arrays.jl
- src/interfaces.jl
- src/meshes.jl
- src/precompile.jl
- src/primitives/rectangles.jl
- src/primitives/spheres.jl
- src/viewtypes.jl
- test/geometrytypes.jl
- test/runtests.jl
This implements the change proposed in https://github.com/JuliaGeometry/GeometryBasics.jl/issues/61 . If the GeometryBasics maintainers are OK with this, I'll make PRs for all the dependents.
> Replace f0 type suffix with f, rename Rect types

- src/metadata.jl
GeometryBasics was using an internal function of StructArrays that was changed during a refactor, this PR avoids depending on internals of StructArrays.
> fix meta_table

- src/triangulation.jl
As this methods seemed very costly in https://github.com/JuliaPlots/Makie.jl/discussions/1636, I thought it could be less taxing on the compiler to remove unused type parameters.
> simplify snip signature

- src/interfaces.jl
- test/geometrytypes.jl
We returned Vector{Point} here
> fix uv eltype

- .github/workflows/ci.yml
- Project.toml
- src/GeometryBasics.jl
- src/basic_types.jl
- src/geointerface.jl
- test/geointerface.jl
- test/runtests.jl
> Implemented GeoInterface.

- src/geointerface.jl
@visr @evetion is there a better way to figure out the eltype?
> use concrete points

- src/geointerface.jl
- test/geointerface.jl
Vectors of geometries were defined as geometries here. But that breaks heaps of the interface as they don't actually return a `geomtrait`.
So removing. No tests as its just deleting things that are bugs.
Another tiny change is using `AbstractMesh` in `isgeometry` instead of `Mesh` because `geomtrait` uses `AbstractMesh`.
> vectors are not `isgeometry` material

- src/meshes.jl
Brings allocations down to a fixed number and improves runtime by about x3 in our application.
Note: `reduce(vcat, ..)` plus broadcasting is faster than `mapreduce` for some reason
> improve merge(meshes)

- Project.toml
- src/GeometryBasics.jl
- src/geointerface.jl
- test/geointerface.jl
- test/runtests.jl
This has been pirated in Tyler and should rather live in GeometryBasics.
This would enable us to use this method in PyramidScheme without having to depend on Tyler for example. 
I put the definition into the GeoInterface file because for me the Extents is an extension of the GeoInterface. 
I am not sure, whether it would make sense to also provide the extent functionality also for higher dimensional rectangles or other geometry types, but the Rect2 is needed for the subsetting in Tyler.
@rafaqz
> Add Extents.extent method for Rect2

- src/geometry_primitives.jl
This PR reduces the use of `push!` in `collect_with_eltype`. 
Unfortunately it's not as good as it could be, because we don't know the eltype of our iterator. Even when it is constant `eltype(iter)` is `Any`. It may be worth writing a custom iterator that keeps `eltype`.
> less `push!` in collect_with_eltype

- src/triangulation.jl
Currently, I observe the following steady increase in memory upon repeated triangulations
eventually leading to OOM errors:
```
julia> using GeometryBasics
julia> points = Point2f.(reverse.(sincos.(0:0.01:2π)));
julia> triang = GeometryBasics.earcut_triangulate([points]);
julia> Sys.maxrss()/2^20
433.01171875
julia> @time for i=1:10^5
GeometryBasics.earcut_triangulate([points]);
end
19.742204 seconds (500.00 k allocations: 30.518 MiB, 0.06% gc time)
julia> GC.gc(true)
julia> Sys.maxrss()/2^20
1156.88671875
julia> @time for i=1:10^5
GeometryBasics.earcut_triangulate([points]);
end
19.175300 seconds (500.00 k allocations: 30.518 MiB)
julia> GC.gc(true)
julia> Sys.maxrss()/2^20
1873.0859375
```
With this PR:
```
julia> points = Point2f.(reverse.(sincos.(0:0.01:2π)));
julia> triang = …
```
> take ownership of triangulation memory - OOM errors

- src/fixed_arrays.jl
- test/fixed_arrays.jl
Also cleans up the implementation to use the functions directly and avoid anonymous functions.
This upstreams some type piracy which I've been doing in GeoMakie for a while.
> Implement `isinf` and `isfinite` for `Point` and `Vec`

- docs/src/index.md
- src/GeometryBasics.jl
- src/basic_types.jl
- src/fixed_arrays.jl
- src/generated-aliases.jl
- src/primitives/rectangles.jl
This PR makes all aliases recognizable by the linter and adds missing ones.
> dont use macro for aliases and introduce more variants (Float64 -> d, UInt -> ui)

- docs/src/primitives.md
- src/GeometryBasics.jl
- src/interfaces.jl
- src/precompiles.jl
- test/geometrytypes.jl
- test/polygons.jl
- test/runtests.jl
Fix https://github.com/JuliaGeometry/GeometryBasics.jl/issues/224.
EDIT: now non-breaking: the deprecated binding `Tesselation` is kept and can be removed later.
> rename `tesselation` to `tessellation`

- .github/workflows/ci.yml
Removes old branches added to doc build
> Get docs building again

- src/basic_types.jl
- src/meshes.jl
- test/geometrytypes.jl
In 0.5 we changed the hash and == functions to consider faces equal under cyclic permutation of their indices. E.g. `(i, j, k) == (j, k, i)`. This leaves the involved vertices, the winding direction and the shape of the face the same, at least for 2D faces. 
This pr reverts that change by moving that functionality into new functions. Equality and hashing require equal ordering after this. I'm not sure if we want the pre or post 0.5 functionality here, but if we do we can merge this.
> Don't consider faces equal under cyclic permutation by default

- src/primitives/rectangles.jl
- test/geometrytypes.jl
Another accidental breaking change
> allow Vectors in Rect

- src/fixed_arrays.jl
- src/geometry_primitives.jl
- src/meshes.jl
- src/triangulation.jl
- test/fixed_arrays.jl
- test/geometrytypes.jl
@ffreyer @SimonDanisch This PR implements the "shoelace" method for normal computation: 
The approach should reduce to the same thing for triangles but generalises properly for faces with more than 3 vertices. Previously 3 points were taken along the face to compute the normal. This assumes that the face/polygon is planar and that the chosen points are not for co-linear edges. However both can naturally occur for faces with more than 3 nodes. Previously such faces would have inaccurate normals computed or NaNs would be returned. 
Here is a test case for a Quad with a co-linear edge, the above implemented method now returns the z-dir as the normal direction properly: 
```
v = [Point{3,Float64}(0.0,0.0,0.0),Point{3,Float64}(1.0,0.0,0.0),Point{3,Float64}(2.0,0.0,0.0),Point{3,Float64}(2.0,1.0, …
```
> Use shoelace approach to compute normals

- .github/workflows/ci.yml
- docs/src/primitives.md
- src/GeometryBasics.jl
- src/primitives/Cone.jl
- src/primitives/cylinders.jl
- test/geometrytypes.jl
I want to remove the mesh generation code in Makie that's used for arrows and add replacements as GeometryPrimitives here. This is coupled with https://github.com/MakieOrg/Makie.jl/pull/4925.
Currently this just adds `Cone()` with the idea of simplifying the arrow components to full, closed meshes.
> Add Cone primitive
